#ifndef FOUR-OPERATION_EXPRESSION_ANALYSE_H_INCLUDED
#define FOUR-OPERATION_EXPRESSION_ANALYSE_H_INCLUDED

#include "polynomial.h"

polynomial analyse(char* exp);

#endif // FOUR-OPERATION_EXPRESSION_ANALYSE_H_INCLUDED
